### ISSUE TITLE
when redis server down 

### ISSUE THREAD

**Issue by iarwen** [mybatis/redis-cache#39] opened 2016-11-08 07:26 UTC
if redis server down,i want direct query from db and not throw exception, how  can i config?

**Comment by smoner** [comment] 2017-02-05 03:27
maybe ,you can catch the exception ,don't throw   and  direct  query  from  db

**Comment by mahaoran** [comment] 2018-06-24 20:50
No follow up?

**Comment by sunpe** [comment] 2018-08-10 09:46
I think should add try-catch to RedisCallback.doWithRedis() to avoid system error. But it's need independent monitor to monitoring reids and mysql.

**Comment by hazendaz** [comment] 2023-11-22 03:43
closing as old and not sure this was intended here as question on redis.

**Closed by hazendaz** 2023-11-22 03:43 UTC
